package com.example.authserver.mapper;

import com.example.authserver.model.Oauth2Authorization;
import com.example.authserver.model.Oauth2AuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Oauth2AuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    long countByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insert(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insertSelective(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    List<Oauth2Authorization> selectByExampleWithBLOBs(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    List<Oauth2Authorization> selectByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    Oauth2Authorization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExampleSelective(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExample(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKeySelective(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKey(Oauth2Authorization row);
}