package com.example.authserver.mapper;

import com.example.authserver.model.Oauth2AuthorizationConsent;
import com.example.authserver.model.Oauth2AuthorizationConsentExample.Criteria;
import com.example.authserver.model.Oauth2AuthorizationConsentExample.Criterion;
import com.example.authserver.model.Oauth2AuthorizationConsentExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class Oauth2AuthorizationConsentSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String countByExample(Oauth2AuthorizationConsentExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("oauth2_authorization_consent");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String deleteByExample(Oauth2AuthorizationConsentExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("oauth2_authorization_consent");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String insertSelective(Oauth2AuthorizationConsent row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("oauth2_authorization_consent");
        
        if (row.getRegisteredClientId() != null) {
            sql.VALUES("registered_client_id", "#{registeredClientId,jdbcType=VARCHAR}");
        }
        
        if (row.getPrincipalName() != null) {
            sql.VALUES("principal_name", "#{principalName,jdbcType=VARCHAR}");
        }
        
        if (row.getAuthorities() != null) {
            sql.VALUES("authorities", "#{authorities,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String selectByExample(Oauth2AuthorizationConsentExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("registered_client_id");
        } else {
            sql.SELECT("registered_client_id");
        }
        sql.SELECT("principal_name");
        sql.SELECT("authorities");
        sql.FROM("oauth2_authorization_consent");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Oauth2AuthorizationConsent row = (Oauth2AuthorizationConsent) parameter.get("row");
        Oauth2AuthorizationConsentExample example = (Oauth2AuthorizationConsentExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorization_consent");
        
        if (row.getRegisteredClientId() != null) {
            sql.SET("registered_client_id = #{row.registeredClientId,jdbcType=VARCHAR}");
        }
        
        if (row.getPrincipalName() != null) {
            sql.SET("principal_name = #{row.principalName,jdbcType=VARCHAR}");
        }
        
        if (row.getAuthorities() != null) {
            sql.SET("authorities = #{row.authorities,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorization_consent");
        
        sql.SET("registered_client_id = #{row.registeredClientId,jdbcType=VARCHAR}");
        sql.SET("principal_name = #{row.principalName,jdbcType=VARCHAR}");
        sql.SET("authorities = #{row.authorities,jdbcType=VARCHAR}");
        
        Oauth2AuthorizationConsentExample example = (Oauth2AuthorizationConsentExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByPrimaryKeySelective(Oauth2AuthorizationConsent row) {
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorization_consent");
        
        if (row.getAuthorities() != null) {
            sql.SET("authorities = #{authorities,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("registered_client_id = #{registeredClientId,jdbcType=VARCHAR}");
        sql.WHERE("principal_name = #{principalName,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    protected void applyWhere(SQL sql, Oauth2AuthorizationConsentExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}