package com.example.authserver.mapper;

import com.example.authserver.model.Oauth2AuthorizationConsent;
import com.example.authserver.model.Oauth2AuthorizationConsentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Oauth2AuthorizationConsentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    long countByExample(Oauth2AuthorizationConsentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByExample(Oauth2AuthorizationConsentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByPrimaryKey(@Param("registeredClientId") String registeredClientId, @Param("principalName") String principalName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insert(Oauth2AuthorizationConsent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insertSelective(Oauth2AuthorizationConsent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    List<Oauth2AuthorizationConsent> selectByExample(Oauth2AuthorizationConsentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    Oauth2AuthorizationConsent selectByPrimaryKey(@Param("registeredClientId") String registeredClientId, @Param("principalName") String principalName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExampleSelective(@Param("row") Oauth2AuthorizationConsent row, @Param("example") Oauth2AuthorizationConsentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExample(@Param("row") Oauth2AuthorizationConsent row, @Param("example") Oauth2AuthorizationConsentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKeySelective(Oauth2AuthorizationConsent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKey(Oauth2AuthorizationConsent row);
}