package com.example.authserver.mapper;

import com.example.authserver.model.Oauth2AuthorizedClient;
import com.example.authserver.model.Oauth2AuthorizedClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Oauth2AuthorizedClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    long countByExample(Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByExample(Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int deleteByPrimaryKey(@Param("clientRegistrationId") String clientRegistrationId, @Param("principalName") String principalName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insert(Oauth2AuthorizedClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int insertSelective(Oauth2AuthorizedClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    List<Oauth2AuthorizedClient> selectByExampleWithBLOBs(Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    List<Oauth2AuthorizedClient> selectByExample(Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    Oauth2AuthorizedClient selectByPrimaryKey(@Param("clientRegistrationId") String clientRegistrationId, @Param("principalName") String principalName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExampleSelective(@Param("row") Oauth2AuthorizedClient row, @Param("example") Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Oauth2AuthorizedClient row, @Param("example") Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByExample(@Param("row") Oauth2AuthorizedClient row, @Param("example") Oauth2AuthorizedClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKeySelective(Oauth2AuthorizedClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Oauth2AuthorizedClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    int updateByPrimaryKey(Oauth2AuthorizedClient row);
}