package com.example.authserver.mapper;

import com.example.authserver.model.Oauth2AuthorizedClient;
import com.example.authserver.model.Oauth2AuthorizedClientExample.Criteria;
import com.example.authserver.model.Oauth2AuthorizedClientExample.Criterion;
import com.example.authserver.model.Oauth2AuthorizedClientExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class Oauth2AuthorizedClientSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String countByExample(Oauth2AuthorizedClientExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("oauth2_authorized_client");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String deleteByExample(Oauth2AuthorizedClientExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("oauth2_authorized_client");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String insertSelective(Oauth2AuthorizedClient row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("oauth2_authorized_client");
        
        if (row.getClientRegistrationId() != null) {
            sql.VALUES("client_registration_id", "#{clientRegistrationId,jdbcType=VARCHAR}");
        }
        
        if (row.getPrincipalName() != null) {
            sql.VALUES("principal_name", "#{principalName,jdbcType=VARCHAR}");
        }
        
        if (row.getAccessTokenType() != null) {
            sql.VALUES("access_token_type", "#{accessTokenType,jdbcType=VARCHAR}");
        }
        
        if (row.getAccessTokenIssuedAt() != null) {
            sql.VALUES("access_token_issued_at", "#{accessTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenExpiresAt() != null) {
            sql.VALUES("access_token_expires_at", "#{accessTokenExpiresAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenScopes() != null) {
            sql.VALUES("access_token_scopes", "#{accessTokenScopes,jdbcType=VARCHAR}");
        }
        
        if (row.getRefreshTokenIssuedAt() != null) {
            sql.VALUES("refresh_token_issued_at", "#{refreshTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreatedAt() != null) {
            sql.VALUES("created_at", "#{createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenValue() != null) {
            sql.VALUES("access_token_value", "#{accessTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        if (row.getRefreshTokenValue() != null) {
            sql.VALUES("refresh_token_value", "#{refreshTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String selectByExampleWithBLOBs(Oauth2AuthorizedClientExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("client_registration_id");
        } else {
            sql.SELECT("client_registration_id");
        }
        sql.SELECT("principal_name");
        sql.SELECT("access_token_type");
        sql.SELECT("access_token_issued_at");
        sql.SELECT("access_token_expires_at");
        sql.SELECT("access_token_scopes");
        sql.SELECT("refresh_token_issued_at");
        sql.SELECT("created_at");
        sql.SELECT("access_token_value");
        sql.SELECT("refresh_token_value");
        sql.FROM("oauth2_authorized_client");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String selectByExample(Oauth2AuthorizedClientExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("client_registration_id");
        } else {
            sql.SELECT("client_registration_id");
        }
        sql.SELECT("principal_name");
        sql.SELECT("access_token_type");
        sql.SELECT("access_token_issued_at");
        sql.SELECT("access_token_expires_at");
        sql.SELECT("access_token_scopes");
        sql.SELECT("refresh_token_issued_at");
        sql.SELECT("created_at");
        sql.FROM("oauth2_authorized_client");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Oauth2AuthorizedClient row = (Oauth2AuthorizedClient) parameter.get("row");
        Oauth2AuthorizedClientExample example = (Oauth2AuthorizedClientExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorized_client");
        
        if (row.getClientRegistrationId() != null) {
            sql.SET("client_registration_id = #{row.clientRegistrationId,jdbcType=VARCHAR}");
        }
        
        if (row.getPrincipalName() != null) {
            sql.SET("principal_name = #{row.principalName,jdbcType=VARCHAR}");
        }
        
        if (row.getAccessTokenType() != null) {
            sql.SET("access_token_type = #{row.accessTokenType,jdbcType=VARCHAR}");
        }
        
        if (row.getAccessTokenIssuedAt() != null) {
            sql.SET("access_token_issued_at = #{row.accessTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenExpiresAt() != null) {
            sql.SET("access_token_expires_at = #{row.accessTokenExpiresAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenScopes() != null) {
            sql.SET("access_token_scopes = #{row.accessTokenScopes,jdbcType=VARCHAR}");
        }
        
        if (row.getRefreshTokenIssuedAt() != null) {
            sql.SET("refresh_token_issued_at = #{row.refreshTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreatedAt() != null) {
            sql.SET("created_at = #{row.createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenValue() != null) {
            sql.SET("access_token_value = #{row.accessTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        if (row.getRefreshTokenValue() != null) {
            sql.SET("refresh_token_value = #{row.refreshTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorized_client");
        
        sql.SET("client_registration_id = #{row.clientRegistrationId,jdbcType=VARCHAR}");
        sql.SET("principal_name = #{row.principalName,jdbcType=VARCHAR}");
        sql.SET("access_token_type = #{row.accessTokenType,jdbcType=VARCHAR}");
        sql.SET("access_token_issued_at = #{row.accessTokenIssuedAt,jdbcType=TIMESTAMP}");
        sql.SET("access_token_expires_at = #{row.accessTokenExpiresAt,jdbcType=TIMESTAMP}");
        sql.SET("access_token_scopes = #{row.accessTokenScopes,jdbcType=VARCHAR}");
        sql.SET("refresh_token_issued_at = #{row.refreshTokenIssuedAt,jdbcType=TIMESTAMP}");
        sql.SET("created_at = #{row.createdAt,jdbcType=TIMESTAMP}");
        sql.SET("access_token_value = #{row.accessTokenValue,jdbcType=LONGVARBINARY}");
        sql.SET("refresh_token_value = #{row.refreshTokenValue,jdbcType=LONGVARBINARY}");
        
        Oauth2AuthorizedClientExample example = (Oauth2AuthorizedClientExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorized_client");
        
        sql.SET("client_registration_id = #{row.clientRegistrationId,jdbcType=VARCHAR}");
        sql.SET("principal_name = #{row.principalName,jdbcType=VARCHAR}");
        sql.SET("access_token_type = #{row.accessTokenType,jdbcType=VARCHAR}");
        sql.SET("access_token_issued_at = #{row.accessTokenIssuedAt,jdbcType=TIMESTAMP}");
        sql.SET("access_token_expires_at = #{row.accessTokenExpiresAt,jdbcType=TIMESTAMP}");
        sql.SET("access_token_scopes = #{row.accessTokenScopes,jdbcType=VARCHAR}");
        sql.SET("refresh_token_issued_at = #{row.refreshTokenIssuedAt,jdbcType=TIMESTAMP}");
        sql.SET("created_at = #{row.createdAt,jdbcType=TIMESTAMP}");
        
        Oauth2AuthorizedClientExample example = (Oauth2AuthorizedClientExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    public String updateByPrimaryKeySelective(Oauth2AuthorizedClient row) {
        SQL sql = new SQL();
        sql.UPDATE("oauth2_authorized_client");
        
        if (row.getAccessTokenType() != null) {
            sql.SET("access_token_type = #{accessTokenType,jdbcType=VARCHAR}");
        }
        
        if (row.getAccessTokenIssuedAt() != null) {
            sql.SET("access_token_issued_at = #{accessTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenExpiresAt() != null) {
            sql.SET("access_token_expires_at = #{accessTokenExpiresAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenScopes() != null) {
            sql.SET("access_token_scopes = #{accessTokenScopes,jdbcType=VARCHAR}");
        }
        
        if (row.getRefreshTokenIssuedAt() != null) {
            sql.SET("refresh_token_issued_at = #{refreshTokenIssuedAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreatedAt() != null) {
            sql.SET("created_at = #{createdAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getAccessTokenValue() != null) {
            sql.SET("access_token_value = #{accessTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        if (row.getRefreshTokenValue() != null) {
            sql.SET("refresh_token_value = #{refreshTokenValue,jdbcType=LONGVARBINARY}");
        }
        
        sql.WHERE("client_registration_id = #{clientRegistrationId,jdbcType=VARCHAR}");
        sql.WHERE("principal_name = #{principalName,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:44:16 CST 2023
     */
    protected void applyWhere(SQL sql, Oauth2AuthorizedClientExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}