package com.example.authserver.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Oauth2AuthorizedClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Oauth2AuthorizedClientExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientRegistrationIdIsNull() {
            addCriterion("client_registration_id is null");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdIsNotNull() {
            addCriterion("client_registration_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdEqualTo(String value) {
            addCriterion("client_registration_id =", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdNotEqualTo(String value) {
            addCriterion("client_registration_id <>", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdGreaterThan(String value) {
            addCriterion("client_registration_id >", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_registration_id >=", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdLessThan(String value) {
            addCriterion("client_registration_id <", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdLessThanOrEqualTo(String value) {
            addCriterion("client_registration_id <=", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdLike(String value) {
            addCriterion("client_registration_id like", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdNotLike(String value) {
            addCriterion("client_registration_id not like", value, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdIn(List<String> values) {
            addCriterion("client_registration_id in", values, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdNotIn(List<String> values) {
            addCriterion("client_registration_id not in", values, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdBetween(String value1, String value2) {
            addCriterion("client_registration_id between", value1, value2, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andClientRegistrationIdNotBetween(String value1, String value2) {
            addCriterion("client_registration_id not between", value1, value2, "clientRegistrationId");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNull() {
            addCriterion("principal_name is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNotNull() {
            addCriterion("principal_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameEqualTo(String value) {
            addCriterion("principal_name =", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotEqualTo(String value) {
            addCriterion("principal_name <>", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThan(String value) {
            addCriterion("principal_name >", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThanOrEqualTo(String value) {
            addCriterion("principal_name >=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThan(String value) {
            addCriterion("principal_name <", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThanOrEqualTo(String value) {
            addCriterion("principal_name <=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLike(String value) {
            addCriterion("principal_name like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotLike(String value) {
            addCriterion("principal_name not like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIn(List<String> values) {
            addCriterion("principal_name in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotIn(List<String> values) {
            addCriterion("principal_name not in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameBetween(String value1, String value2) {
            addCriterion("principal_name between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotBetween(String value1, String value2) {
            addCriterion("principal_name not between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNull() {
            addCriterion("access_token_type is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNotNull() {
            addCriterion("access_token_type is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeEqualTo(String value) {
            addCriterion("access_token_type =", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotEqualTo(String value) {
            addCriterion("access_token_type <>", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThan(String value) {
            addCriterion("access_token_type >", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("access_token_type >=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThan(String value) {
            addCriterion("access_token_type <", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThanOrEqualTo(String value) {
            addCriterion("access_token_type <=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLike(String value) {
            addCriterion("access_token_type like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotLike(String value) {
            addCriterion("access_token_type not like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIn(List<String> values) {
            addCriterion("access_token_type in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotIn(List<String> values) {
            addCriterion("access_token_type not in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeBetween(String value1, String value2) {
            addCriterion("access_token_type between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotBetween(String value1, String value2) {
            addCriterion("access_token_type not between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNull() {
            addCriterion("access_token_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNotNull() {
            addCriterion("access_token_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtEqualTo(Date value) {
            addCriterion("access_token_issued_at =", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotEqualTo(Date value) {
            addCriterion("access_token_issued_at <>", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThan(Date value) {
            addCriterion("access_token_issued_at >", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("access_token_issued_at >=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThan(Date value) {
            addCriterion("access_token_issued_at <", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("access_token_issued_at <=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIn(List<Date> values) {
            addCriterion("access_token_issued_at in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotIn(List<Date> values) {
            addCriterion("access_token_issued_at not in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtBetween(Date value1, Date value2) {
            addCriterion("access_token_issued_at between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("access_token_issued_at not between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNull() {
            addCriterion("access_token_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNotNull() {
            addCriterion("access_token_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtEqualTo(Date value) {
            addCriterion("access_token_expires_at =", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotEqualTo(Date value) {
            addCriterion("access_token_expires_at <>", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThan(Date value) {
            addCriterion("access_token_expires_at >", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("access_token_expires_at >=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThan(Date value) {
            addCriterion("access_token_expires_at <", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("access_token_expires_at <=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIn(List<Date> values) {
            addCriterion("access_token_expires_at in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotIn(List<Date> values) {
            addCriterion("access_token_expires_at not in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtBetween(Date value1, Date value2) {
            addCriterion("access_token_expires_at between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("access_token_expires_at not between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNull() {
            addCriterion("access_token_scopes is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNotNull() {
            addCriterion("access_token_scopes is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesEqualTo(String value) {
            addCriterion("access_token_scopes =", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotEqualTo(String value) {
            addCriterion("access_token_scopes <>", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThan(String value) {
            addCriterion("access_token_scopes >", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThanOrEqualTo(String value) {
            addCriterion("access_token_scopes >=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThan(String value) {
            addCriterion("access_token_scopes <", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThanOrEqualTo(String value) {
            addCriterion("access_token_scopes <=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLike(String value) {
            addCriterion("access_token_scopes like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotLike(String value) {
            addCriterion("access_token_scopes not like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIn(List<String> values) {
            addCriterion("access_token_scopes in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotIn(List<String> values) {
            addCriterion("access_token_scopes not in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesBetween(String value1, String value2) {
            addCriterion("access_token_scopes between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotBetween(String value1, String value2) {
            addCriterion("access_token_scopes not between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNull() {
            addCriterion("refresh_token_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNotNull() {
            addCriterion("refresh_token_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtEqualTo(Date value) {
            addCriterion("refresh_token_issued_at =", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotEqualTo(Date value) {
            addCriterion("refresh_token_issued_at <>", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThan(Date value) {
            addCriterion("refresh_token_issued_at >", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("refresh_token_issued_at >=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThan(Date value) {
            addCriterion("refresh_token_issued_at <", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("refresh_token_issued_at <=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIn(List<Date> values) {
            addCriterion("refresh_token_issued_at in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotIn(List<Date> values) {
            addCriterion("refresh_token_issued_at not in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtBetween(Date value1, Date value2) {
            addCriterion("refresh_token_issued_at between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("refresh_token_issued_at not between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 31 10:45:16 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}