package com.example.authserver.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Oauth2AuthorizationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Oauth2AuthorizationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIsNull() {
            addCriterion("registered_client_id is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIsNotNull() {
            addCriterion("registered_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdEqualTo(String value) {
            addCriterion("registered_client_id =", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotEqualTo(String value) {
            addCriterion("registered_client_id <>", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdGreaterThan(String value) {
            addCriterion("registered_client_id >", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("registered_client_id >=", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLessThan(String value) {
            addCriterion("registered_client_id <", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLessThanOrEqualTo(String value) {
            addCriterion("registered_client_id <=", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLike(String value) {
            addCriterion("registered_client_id like", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotLike(String value) {
            addCriterion("registered_client_id not like", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIn(List<String> values) {
            addCriterion("registered_client_id in", values, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotIn(List<String> values) {
            addCriterion("registered_client_id not in", values, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdBetween(String value1, String value2) {
            addCriterion("registered_client_id between", value1, value2, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotBetween(String value1, String value2) {
            addCriterion("registered_client_id not between", value1, value2, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNull() {
            addCriterion("principal_name is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNotNull() {
            addCriterion("principal_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameEqualTo(String value) {
            addCriterion("principal_name =", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotEqualTo(String value) {
            addCriterion("principal_name <>", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThan(String value) {
            addCriterion("principal_name >", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThanOrEqualTo(String value) {
            addCriterion("principal_name >=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThan(String value) {
            addCriterion("principal_name <", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThanOrEqualTo(String value) {
            addCriterion("principal_name <=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLike(String value) {
            addCriterion("principal_name like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotLike(String value) {
            addCriterion("principal_name not like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIn(List<String> values) {
            addCriterion("principal_name in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotIn(List<String> values) {
            addCriterion("principal_name not in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameBetween(String value1, String value2) {
            addCriterion("principal_name between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotBetween(String value1, String value2) {
            addCriterion("principal_name not between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIsNull() {
            addCriterion("authorization_grant_type is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIsNotNull() {
            addCriterion("authorization_grant_type is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeEqualTo(String value) {
            addCriterion("authorization_grant_type =", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotEqualTo(String value) {
            addCriterion("authorization_grant_type <>", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeGreaterThan(String value) {
            addCriterion("authorization_grant_type >", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeGreaterThanOrEqualTo(String value) {
            addCriterion("authorization_grant_type >=", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLessThan(String value) {
            addCriterion("authorization_grant_type <", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLessThanOrEqualTo(String value) {
            addCriterion("authorization_grant_type <=", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLike(String value) {
            addCriterion("authorization_grant_type like", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotLike(String value) {
            addCriterion("authorization_grant_type not like", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIn(List<String> values) {
            addCriterion("authorization_grant_type in", values, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotIn(List<String> values) {
            addCriterion("authorization_grant_type not in", values, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeBetween(String value1, String value2) {
            addCriterion("authorization_grant_type between", value1, value2, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotBetween(String value1, String value2) {
            addCriterion("authorization_grant_type not between", value1, value2, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesIsNull() {
            addCriterion("authorized_scopes is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesIsNotNull() {
            addCriterion("authorized_scopes is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesEqualTo(String value) {
            addCriterion("authorized_scopes =", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesNotEqualTo(String value) {
            addCriterion("authorized_scopes <>", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesGreaterThan(String value) {
            addCriterion("authorized_scopes >", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesGreaterThanOrEqualTo(String value) {
            addCriterion("authorized_scopes >=", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesLessThan(String value) {
            addCriterion("authorized_scopes <", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesLessThanOrEqualTo(String value) {
            addCriterion("authorized_scopes <=", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesLike(String value) {
            addCriterion("authorized_scopes like", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesNotLike(String value) {
            addCriterion("authorized_scopes not like", value, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesIn(List<String> values) {
            addCriterion("authorized_scopes in", values, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesNotIn(List<String> values) {
            addCriterion("authorized_scopes not in", values, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesBetween(String value1, String value2) {
            addCriterion("authorized_scopes between", value1, value2, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedScopesNotBetween(String value1, String value2) {
            addCriterion("authorized_scopes not between", value1, value2, "authorizedScopes");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIsNull() {
            addCriterion("authorization_code_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIsNotNull() {
            addCriterion("authorization_code_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtEqualTo(Date value) {
            addCriterion("authorization_code_issued_at =", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotEqualTo(Date value) {
            addCriterion("authorization_code_issued_at <>", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtGreaterThan(Date value) {
            addCriterion("authorization_code_issued_at >", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("authorization_code_issued_at >=", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtLessThan(Date value) {
            addCriterion("authorization_code_issued_at <", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("authorization_code_issued_at <=", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIn(List<Date> values) {
            addCriterion("authorization_code_issued_at in", values, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotIn(List<Date> values) {
            addCriterion("authorization_code_issued_at not in", values, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtBetween(Date value1, Date value2) {
            addCriterion("authorization_code_issued_at between", value1, value2, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("authorization_code_issued_at not between", value1, value2, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIsNull() {
            addCriterion("authorization_code_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIsNotNull() {
            addCriterion("authorization_code_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtEqualTo(Date value) {
            addCriterion("authorization_code_expires_at =", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotEqualTo(Date value) {
            addCriterion("authorization_code_expires_at <>", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtGreaterThan(Date value) {
            addCriterion("authorization_code_expires_at >", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("authorization_code_expires_at >=", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtLessThan(Date value) {
            addCriterion("authorization_code_expires_at <", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("authorization_code_expires_at <=", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIn(List<Date> values) {
            addCriterion("authorization_code_expires_at in", values, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotIn(List<Date> values) {
            addCriterion("authorization_code_expires_at not in", values, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtBetween(Date value1, Date value2) {
            addCriterion("authorization_code_expires_at between", value1, value2, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("authorization_code_expires_at not between", value1, value2, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNull() {
            addCriterion("access_token_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNotNull() {
            addCriterion("access_token_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtEqualTo(Date value) {
            addCriterion("access_token_issued_at =", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotEqualTo(Date value) {
            addCriterion("access_token_issued_at <>", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThan(Date value) {
            addCriterion("access_token_issued_at >", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("access_token_issued_at >=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThan(Date value) {
            addCriterion("access_token_issued_at <", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("access_token_issued_at <=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIn(List<Date> values) {
            addCriterion("access_token_issued_at in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotIn(List<Date> values) {
            addCriterion("access_token_issued_at not in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtBetween(Date value1, Date value2) {
            addCriterion("access_token_issued_at between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("access_token_issued_at not between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNull() {
            addCriterion("access_token_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNotNull() {
            addCriterion("access_token_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtEqualTo(Date value) {
            addCriterion("access_token_expires_at =", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotEqualTo(Date value) {
            addCriterion("access_token_expires_at <>", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThan(Date value) {
            addCriterion("access_token_expires_at >", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("access_token_expires_at >=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThan(Date value) {
            addCriterion("access_token_expires_at <", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("access_token_expires_at <=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIn(List<Date> values) {
            addCriterion("access_token_expires_at in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotIn(List<Date> values) {
            addCriterion("access_token_expires_at not in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtBetween(Date value1, Date value2) {
            addCriterion("access_token_expires_at between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("access_token_expires_at not between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNull() {
            addCriterion("access_token_type is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNotNull() {
            addCriterion("access_token_type is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeEqualTo(String value) {
            addCriterion("access_token_type =", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotEqualTo(String value) {
            addCriterion("access_token_type <>", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThan(String value) {
            addCriterion("access_token_type >", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("access_token_type >=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThan(String value) {
            addCriterion("access_token_type <", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThanOrEqualTo(String value) {
            addCriterion("access_token_type <=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLike(String value) {
            addCriterion("access_token_type like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotLike(String value) {
            addCriterion("access_token_type not like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIn(List<String> values) {
            addCriterion("access_token_type in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotIn(List<String> values) {
            addCriterion("access_token_type not in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeBetween(String value1, String value2) {
            addCriterion("access_token_type between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotBetween(String value1, String value2) {
            addCriterion("access_token_type not between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNull() {
            addCriterion("access_token_scopes is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNotNull() {
            addCriterion("access_token_scopes is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesEqualTo(String value) {
            addCriterion("access_token_scopes =", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotEqualTo(String value) {
            addCriterion("access_token_scopes <>", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThan(String value) {
            addCriterion("access_token_scopes >", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThanOrEqualTo(String value) {
            addCriterion("access_token_scopes >=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThan(String value) {
            addCriterion("access_token_scopes <", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThanOrEqualTo(String value) {
            addCriterion("access_token_scopes <=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLike(String value) {
            addCriterion("access_token_scopes like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotLike(String value) {
            addCriterion("access_token_scopes not like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIn(List<String> values) {
            addCriterion("access_token_scopes in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotIn(List<String> values) {
            addCriterion("access_token_scopes not in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesBetween(String value1, String value2) {
            addCriterion("access_token_scopes between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotBetween(String value1, String value2) {
            addCriterion("access_token_scopes not between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIsNull() {
            addCriterion("oidc_id_token_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIsNotNull() {
            addCriterion("oidc_id_token_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtEqualTo(Date value) {
            addCriterion("oidc_id_token_issued_at =", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotEqualTo(Date value) {
            addCriterion("oidc_id_token_issued_at <>", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtGreaterThan(Date value) {
            addCriterion("oidc_id_token_issued_at >", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("oidc_id_token_issued_at >=", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtLessThan(Date value) {
            addCriterion("oidc_id_token_issued_at <", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("oidc_id_token_issued_at <=", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIn(List<Date> values) {
            addCriterion("oidc_id_token_issued_at in", values, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotIn(List<Date> values) {
            addCriterion("oidc_id_token_issued_at not in", values, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtBetween(Date value1, Date value2) {
            addCriterion("oidc_id_token_issued_at between", value1, value2, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("oidc_id_token_issued_at not between", value1, value2, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIsNull() {
            addCriterion("oidc_id_token_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIsNotNull() {
            addCriterion("oidc_id_token_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtEqualTo(Date value) {
            addCriterion("oidc_id_token_expires_at =", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotEqualTo(Date value) {
            addCriterion("oidc_id_token_expires_at <>", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtGreaterThan(Date value) {
            addCriterion("oidc_id_token_expires_at >", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("oidc_id_token_expires_at >=", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtLessThan(Date value) {
            addCriterion("oidc_id_token_expires_at <", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("oidc_id_token_expires_at <=", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIn(List<Date> values) {
            addCriterion("oidc_id_token_expires_at in", values, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotIn(List<Date> values) {
            addCriterion("oidc_id_token_expires_at not in", values, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtBetween(Date value1, Date value2) {
            addCriterion("oidc_id_token_expires_at between", value1, value2, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("oidc_id_token_expires_at not between", value1, value2, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNull() {
            addCriterion("refresh_token_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNotNull() {
            addCriterion("refresh_token_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtEqualTo(Date value) {
            addCriterion("refresh_token_issued_at =", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotEqualTo(Date value) {
            addCriterion("refresh_token_issued_at <>", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThan(Date value) {
            addCriterion("refresh_token_issued_at >", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("refresh_token_issued_at >=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThan(Date value) {
            addCriterion("refresh_token_issued_at <", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("refresh_token_issued_at <=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIn(List<Date> values) {
            addCriterion("refresh_token_issued_at in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotIn(List<Date> values) {
            addCriterion("refresh_token_issued_at not in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtBetween(Date value1, Date value2) {
            addCriterion("refresh_token_issued_at between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("refresh_token_issued_at not between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIsNull() {
            addCriterion("refresh_token_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIsNotNull() {
            addCriterion("refresh_token_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtEqualTo(Date value) {
            addCriterion("refresh_token_expires_at =", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotEqualTo(Date value) {
            addCriterion("refresh_token_expires_at <>", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtGreaterThan(Date value) {
            addCriterion("refresh_token_expires_at >", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("refresh_token_expires_at >=", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtLessThan(Date value) {
            addCriterion("refresh_token_expires_at <", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("refresh_token_expires_at <=", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIn(List<Date> values) {
            addCriterion("refresh_token_expires_at in", values, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotIn(List<Date> values) {
            addCriterion("refresh_token_expires_at not in", values, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtBetween(Date value1, Date value2) {
            addCriterion("refresh_token_expires_at between", value1, value2, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("refresh_token_expires_at not between", value1, value2, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtIsNull() {
            addCriterion("user_code_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtIsNotNull() {
            addCriterion("user_code_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtEqualTo(Date value) {
            addCriterion("user_code_issued_at =", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtNotEqualTo(Date value) {
            addCriterion("user_code_issued_at <>", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtGreaterThan(Date value) {
            addCriterion("user_code_issued_at >", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("user_code_issued_at >=", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtLessThan(Date value) {
            addCriterion("user_code_issued_at <", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("user_code_issued_at <=", value, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtIn(List<Date> values) {
            addCriterion("user_code_issued_at in", values, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtNotIn(List<Date> values) {
            addCriterion("user_code_issued_at not in", values, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtBetween(Date value1, Date value2) {
            addCriterion("user_code_issued_at between", value1, value2, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("user_code_issued_at not between", value1, value2, "userCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtIsNull() {
            addCriterion("user_code_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtIsNotNull() {
            addCriterion("user_code_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtEqualTo(Date value) {
            addCriterion("user_code_expires_at =", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtNotEqualTo(Date value) {
            addCriterion("user_code_expires_at <>", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtGreaterThan(Date value) {
            addCriterion("user_code_expires_at >", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("user_code_expires_at >=", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtLessThan(Date value) {
            addCriterion("user_code_expires_at <", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("user_code_expires_at <=", value, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtIn(List<Date> values) {
            addCriterion("user_code_expires_at in", values, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtNotIn(List<Date> values) {
            addCriterion("user_code_expires_at not in", values, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtBetween(Date value1, Date value2) {
            addCriterion("user_code_expires_at between", value1, value2, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserCodeExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("user_code_expires_at not between", value1, value2, "userCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtIsNull() {
            addCriterion("device_code_issued_at is null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtIsNotNull() {
            addCriterion("device_code_issued_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtEqualTo(Date value) {
            addCriterion("device_code_issued_at =", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtNotEqualTo(Date value) {
            addCriterion("device_code_issued_at <>", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtGreaterThan(Date value) {
            addCriterion("device_code_issued_at >", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("device_code_issued_at >=", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtLessThan(Date value) {
            addCriterion("device_code_issued_at <", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtLessThanOrEqualTo(Date value) {
            addCriterion("device_code_issued_at <=", value, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtIn(List<Date> values) {
            addCriterion("device_code_issued_at in", values, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtNotIn(List<Date> values) {
            addCriterion("device_code_issued_at not in", values, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtBetween(Date value1, Date value2) {
            addCriterion("device_code_issued_at between", value1, value2, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIssuedAtNotBetween(Date value1, Date value2) {
            addCriterion("device_code_issued_at not between", value1, value2, "deviceCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtIsNull() {
            addCriterion("device_code_expires_at is null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtIsNotNull() {
            addCriterion("device_code_expires_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtEqualTo(Date value) {
            addCriterion("device_code_expires_at =", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtNotEqualTo(Date value) {
            addCriterion("device_code_expires_at <>", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtGreaterThan(Date value) {
            addCriterion("device_code_expires_at >", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("device_code_expires_at >=", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtLessThan(Date value) {
            addCriterion("device_code_expires_at <", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("device_code_expires_at <=", value, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtIn(List<Date> values) {
            addCriterion("device_code_expires_at in", values, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtNotIn(List<Date> values) {
            addCriterion("device_code_expires_at not in", values, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtBetween(Date value1, Date value2) {
            addCriterion("device_code_expires_at between", value1, value2, "deviceCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("device_code_expires_at not between", value1, value2, "deviceCodeExpiresAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 31 10:45:16 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}