package com.example.authserver.model;

import java.io.Serializable;
import java.util.Date;

public class Oauth2RegisteredClient implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_id_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date clientIdIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_secret
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_secret_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date clientSecretExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_authentication_methods
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientAuthenticationMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.authorization_grant_types
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String authorizationGrantTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String redirectUris;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.post_logout_redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String postLogoutRedirectUris;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String scopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientSettings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.token_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String tokenSettings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.id
     *
     * @return the value of oauth2_registered_client.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.id
     *
     * @param id the value for oauth2_registered_client.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_id
     *
     * @return the value of oauth2_registered_client.client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_id
     *
     * @param clientId the value for oauth2_registered_client.client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_id_issued_at
     *
     * @return the value of oauth2_registered_client.client_id_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getClientIdIssuedAt() {
        return clientIdIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_id_issued_at
     *
     * @param clientIdIssuedAt the value for oauth2_registered_client.client_id_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientIdIssuedAt(Date clientIdIssuedAt) {
        this.clientIdIssuedAt = clientIdIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_secret
     *
     * @return the value of oauth2_registered_client.client_secret
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_secret
     *
     * @param clientSecret the value for oauth2_registered_client.client_secret
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_secret_expires_at
     *
     * @return the value of oauth2_registered_client.client_secret_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getClientSecretExpiresAt() {
        return clientSecretExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_secret_expires_at
     *
     * @param clientSecretExpiresAt the value for oauth2_registered_client.client_secret_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientSecretExpiresAt(Date clientSecretExpiresAt) {
        this.clientSecretExpiresAt = clientSecretExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_name
     *
     * @return the value of oauth2_registered_client.client_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_name
     *
     * @param clientName the value for oauth2_registered_client.client_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_authentication_methods
     *
     * @return the value of oauth2_registered_client.client_authentication_methods
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientAuthenticationMethods() {
        return clientAuthenticationMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_authentication_methods
     *
     * @param clientAuthenticationMethods the value for oauth2_registered_client.client_authentication_methods
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientAuthenticationMethods(String clientAuthenticationMethods) {
        this.clientAuthenticationMethods = clientAuthenticationMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.authorization_grant_types
     *
     * @return the value of oauth2_registered_client.authorization_grant_types
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAuthorizationGrantTypes() {
        return authorizationGrantTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.authorization_grant_types
     *
     * @param authorizationGrantTypes the value for oauth2_registered_client.authorization_grant_types
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationGrantTypes(String authorizationGrantTypes) {
        this.authorizationGrantTypes = authorizationGrantTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.redirect_uris
     *
     * @return the value of oauth2_registered_client.redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getRedirectUris() {
        return redirectUris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.redirect_uris
     *
     * @param redirectUris the value for oauth2_registered_client.redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRedirectUris(String redirectUris) {
        this.redirectUris = redirectUris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.post_logout_redirect_uris
     *
     * @return the value of oauth2_registered_client.post_logout_redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getPostLogoutRedirectUris() {
        return postLogoutRedirectUris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.post_logout_redirect_uris
     *
     * @param postLogoutRedirectUris the value for oauth2_registered_client.post_logout_redirect_uris
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setPostLogoutRedirectUris(String postLogoutRedirectUris) {
        this.postLogoutRedirectUris = postLogoutRedirectUris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.scopes
     *
     * @return the value of oauth2_registered_client.scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getScopes() {
        return scopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.scopes
     *
     * @param scopes the value for oauth2_registered_client.scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setScopes(String scopes) {
        this.scopes = scopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.client_settings
     *
     * @return the value of oauth2_registered_client.client_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientSettings() {
        return clientSettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.client_settings
     *
     * @param clientSettings the value for oauth2_registered_client.client_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientSettings(String clientSettings) {
        this.clientSettings = clientSettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_registered_client.token_settings
     *
     * @return the value of oauth2_registered_client.token_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getTokenSettings() {
        return tokenSettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_registered_client.token_settings
     *
     * @param tokenSettings the value for oauth2_registered_client.token_settings
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setTokenSettings(String tokenSettings) {
        this.tokenSettings = tokenSettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", clientId=").append(clientId);
        sb.append(", clientIdIssuedAt=").append(clientIdIssuedAt);
        sb.append(", clientSecret=").append(clientSecret);
        sb.append(", clientSecretExpiresAt=").append(clientSecretExpiresAt);
        sb.append(", clientName=").append(clientName);
        sb.append(", clientAuthenticationMethods=").append(clientAuthenticationMethods);
        sb.append(", authorizationGrantTypes=").append(authorizationGrantTypes);
        sb.append(", redirectUris=").append(redirectUris);
        sb.append(", postLogoutRedirectUris=").append(postLogoutRedirectUris);
        sb.append(", scopes=").append(scopes);
        sb.append(", clientSettings=").append(clientSettings);
        sb.append(", tokenSettings=").append(tokenSettings);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}