package com.example.authserver.model;

import java.io.Serializable;
import java.util.Date;

public class Oauth2AuthorizedClient implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.client_registration_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String clientRegistrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String principalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String accessTokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date accessTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date accessTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String accessTokenScopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date refreshTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.created_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] accessTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorized_client.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] refreshTokenValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.client_registration_id
     *
     * @return the value of oauth2_authorized_client.client_registration_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getClientRegistrationId() {
        return clientRegistrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.client_registration_id
     *
     * @param clientRegistrationId the value for oauth2_authorized_client.client_registration_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setClientRegistrationId(String clientRegistrationId) {
        this.clientRegistrationId = clientRegistrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.principal_name
     *
     * @return the value of oauth2_authorized_client.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.principal_name
     *
     * @param principalName the value for oauth2_authorized_client.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.access_token_type
     *
     * @return the value of oauth2_authorized_client.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAccessTokenType() {
        return accessTokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.access_token_type
     *
     * @param accessTokenType the value for oauth2_authorized_client.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenType(String accessTokenType) {
        this.accessTokenType = accessTokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.access_token_issued_at
     *
     * @return the value of oauth2_authorized_client.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAccessTokenIssuedAt() {
        return accessTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.access_token_issued_at
     *
     * @param accessTokenIssuedAt the value for oauth2_authorized_client.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenIssuedAt(Date accessTokenIssuedAt) {
        this.accessTokenIssuedAt = accessTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.access_token_expires_at
     *
     * @return the value of oauth2_authorized_client.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAccessTokenExpiresAt() {
        return accessTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.access_token_expires_at
     *
     * @param accessTokenExpiresAt the value for oauth2_authorized_client.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenExpiresAt(Date accessTokenExpiresAt) {
        this.accessTokenExpiresAt = accessTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.access_token_scopes
     *
     * @return the value of oauth2_authorized_client.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAccessTokenScopes() {
        return accessTokenScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.access_token_scopes
     *
     * @param accessTokenScopes the value for oauth2_authorized_client.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenScopes(String accessTokenScopes) {
        this.accessTokenScopes = accessTokenScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.refresh_token_issued_at
     *
     * @return the value of oauth2_authorized_client.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getRefreshTokenIssuedAt() {
        return refreshTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.refresh_token_issued_at
     *
     * @param refreshTokenIssuedAt the value for oauth2_authorized_client.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenIssuedAt(Date refreshTokenIssuedAt) {
        this.refreshTokenIssuedAt = refreshTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.created_at
     *
     * @return the value of oauth2_authorized_client.created_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.created_at
     *
     * @param createdAt the value for oauth2_authorized_client.created_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.access_token_value
     *
     * @return the value of oauth2_authorized_client.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAccessTokenValue() {
        return accessTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.access_token_value
     *
     * @param accessTokenValue the value for oauth2_authorized_client.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenValue(byte[] accessTokenValue) {
        this.accessTokenValue = accessTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorized_client.refresh_token_value
     *
     * @return the value of oauth2_authorized_client.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getRefreshTokenValue() {
        return refreshTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorized_client.refresh_token_value
     *
     * @param refreshTokenValue the value for oauth2_authorized_client.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenValue(byte[] refreshTokenValue) {
        this.refreshTokenValue = refreshTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorized_client
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientRegistrationId=").append(clientRegistrationId);
        sb.append(", principalName=").append(principalName);
        sb.append(", accessTokenType=").append(accessTokenType);
        sb.append(", accessTokenIssuedAt=").append(accessTokenIssuedAt);
        sb.append(", accessTokenExpiresAt=").append(accessTokenExpiresAt);
        sb.append(", accessTokenScopes=").append(accessTokenScopes);
        sb.append(", refreshTokenIssuedAt=").append(refreshTokenIssuedAt);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", accessTokenValue=").append(accessTokenValue);
        sb.append(", refreshTokenValue=").append(refreshTokenValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}