package com.example.authserver.model;

import java.io.Serializable;
import java.util.Date;

public class Oauth2Authorization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String registeredClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String principalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_grant_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String authorizationGrantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorized_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String authorizedScopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.state
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date authorizationCodeIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date authorizationCodeExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date accessTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date accessTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String accessTokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String accessTokenScopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date oidcIdTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date oidcIdTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date refreshTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date refreshTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.user_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date userCodeIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.user_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date userCodeExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.device_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date deviceCodeIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.device_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private Date deviceCodeExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.attributes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] authorizationCodeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] authorizationCodeMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] accessTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] accessTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] oidcIdTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] oidcIdTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] refreshTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] refreshTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.user_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] userCodeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.user_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] userCodeMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.device_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] deviceCodeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.device_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private byte[] deviceCodeMetadata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.id
     *
     * @return the value of oauth2_authorization.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.id
     *
     * @param id the value for oauth2_authorization.id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.registered_client_id
     *
     * @return the value of oauth2_authorization.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getRegisteredClientId() {
        return registeredClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.registered_client_id
     *
     * @param registeredClientId the value for oauth2_authorization.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRegisteredClientId(String registeredClientId) {
        this.registeredClientId = registeredClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.principal_name
     *
     * @return the value of oauth2_authorization.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.principal_name
     *
     * @param principalName the value for oauth2_authorization.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorization_grant_type
     *
     * @return the value of oauth2_authorization.authorization_grant_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAuthorizationGrantType() {
        return authorizationGrantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorization_grant_type
     *
     * @param authorizationGrantType the value for oauth2_authorization.authorization_grant_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationGrantType(String authorizationGrantType) {
        this.authorizationGrantType = authorizationGrantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorized_scopes
     *
     * @return the value of oauth2_authorization.authorized_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAuthorizedScopes() {
        return authorizedScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorized_scopes
     *
     * @param authorizedScopes the value for oauth2_authorization.authorized_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizedScopes(String authorizedScopes) {
        this.authorizedScopes = authorizedScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.state
     *
     * @return the value of oauth2_authorization.state
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.state
     *
     * @param state the value for oauth2_authorization.state
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorization_code_issued_at
     *
     * @return the value of oauth2_authorization.authorization_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAuthorizationCodeIssuedAt() {
        return authorizationCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorization_code_issued_at
     *
     * @param authorizationCodeIssuedAt the value for oauth2_authorization.authorization_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationCodeIssuedAt(Date authorizationCodeIssuedAt) {
        this.authorizationCodeIssuedAt = authorizationCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorization_code_expires_at
     *
     * @return the value of oauth2_authorization.authorization_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAuthorizationCodeExpiresAt() {
        return authorizationCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorization_code_expires_at
     *
     * @param authorizationCodeExpiresAt the value for oauth2_authorization.authorization_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationCodeExpiresAt(Date authorizationCodeExpiresAt) {
        this.authorizationCodeExpiresAt = authorizationCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_issued_at
     *
     * @return the value of oauth2_authorization.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAccessTokenIssuedAt() {
        return accessTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_issued_at
     *
     * @param accessTokenIssuedAt the value for oauth2_authorization.access_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenIssuedAt(Date accessTokenIssuedAt) {
        this.accessTokenIssuedAt = accessTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_expires_at
     *
     * @return the value of oauth2_authorization.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getAccessTokenExpiresAt() {
        return accessTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_expires_at
     *
     * @param accessTokenExpiresAt the value for oauth2_authorization.access_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenExpiresAt(Date accessTokenExpiresAt) {
        this.accessTokenExpiresAt = accessTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_type
     *
     * @return the value of oauth2_authorization.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAccessTokenType() {
        return accessTokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_type
     *
     * @param accessTokenType the value for oauth2_authorization.access_token_type
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenType(String accessTokenType) {
        this.accessTokenType = accessTokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_scopes
     *
     * @return the value of oauth2_authorization.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAccessTokenScopes() {
        return accessTokenScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_scopes
     *
     * @param accessTokenScopes the value for oauth2_authorization.access_token_scopes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenScopes(String accessTokenScopes) {
        this.accessTokenScopes = accessTokenScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.oidc_id_token_issued_at
     *
     * @return the value of oauth2_authorization.oidc_id_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getOidcIdTokenIssuedAt() {
        return oidcIdTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.oidc_id_token_issued_at
     *
     * @param oidcIdTokenIssuedAt the value for oauth2_authorization.oidc_id_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOidcIdTokenIssuedAt(Date oidcIdTokenIssuedAt) {
        this.oidcIdTokenIssuedAt = oidcIdTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.oidc_id_token_expires_at
     *
     * @return the value of oauth2_authorization.oidc_id_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getOidcIdTokenExpiresAt() {
        return oidcIdTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.oidc_id_token_expires_at
     *
     * @param oidcIdTokenExpiresAt the value for oauth2_authorization.oidc_id_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOidcIdTokenExpiresAt(Date oidcIdTokenExpiresAt) {
        this.oidcIdTokenExpiresAt = oidcIdTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.refresh_token_issued_at
     *
     * @return the value of oauth2_authorization.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getRefreshTokenIssuedAt() {
        return refreshTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.refresh_token_issued_at
     *
     * @param refreshTokenIssuedAt the value for oauth2_authorization.refresh_token_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenIssuedAt(Date refreshTokenIssuedAt) {
        this.refreshTokenIssuedAt = refreshTokenIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.refresh_token_expires_at
     *
     * @return the value of oauth2_authorization.refresh_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getRefreshTokenExpiresAt() {
        return refreshTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.refresh_token_expires_at
     *
     * @param refreshTokenExpiresAt the value for oauth2_authorization.refresh_token_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenExpiresAt(Date refreshTokenExpiresAt) {
        this.refreshTokenExpiresAt = refreshTokenExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.user_code_issued_at
     *
     * @return the value of oauth2_authorization.user_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getUserCodeIssuedAt() {
        return userCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.user_code_issued_at
     *
     * @param userCodeIssuedAt the value for oauth2_authorization.user_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setUserCodeIssuedAt(Date userCodeIssuedAt) {
        this.userCodeIssuedAt = userCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.user_code_expires_at
     *
     * @return the value of oauth2_authorization.user_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getUserCodeExpiresAt() {
        return userCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.user_code_expires_at
     *
     * @param userCodeExpiresAt the value for oauth2_authorization.user_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setUserCodeExpiresAt(Date userCodeExpiresAt) {
        this.userCodeExpiresAt = userCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.device_code_issued_at
     *
     * @return the value of oauth2_authorization.device_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getDeviceCodeIssuedAt() {
        return deviceCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.device_code_issued_at
     *
     * @param deviceCodeIssuedAt the value for oauth2_authorization.device_code_issued_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDeviceCodeIssuedAt(Date deviceCodeIssuedAt) {
        this.deviceCodeIssuedAt = deviceCodeIssuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.device_code_expires_at
     *
     * @return the value of oauth2_authorization.device_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public Date getDeviceCodeExpiresAt() {
        return deviceCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.device_code_expires_at
     *
     * @param deviceCodeExpiresAt the value for oauth2_authorization.device_code_expires_at
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDeviceCodeExpiresAt(Date deviceCodeExpiresAt) {
        this.deviceCodeExpiresAt = deviceCodeExpiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.attributes
     *
     * @return the value of oauth2_authorization.attributes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.attributes
     *
     * @param attributes the value for oauth2_authorization.attributes
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAttributes(byte[] attributes) {
        this.attributes = attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorization_code_value
     *
     * @return the value of oauth2_authorization.authorization_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAuthorizationCodeValue() {
        return authorizationCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorization_code_value
     *
     * @param authorizationCodeValue the value for oauth2_authorization.authorization_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationCodeValue(byte[] authorizationCodeValue) {
        this.authorizationCodeValue = authorizationCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.authorization_code_metadata
     *
     * @return the value of oauth2_authorization.authorization_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAuthorizationCodeMetadata() {
        return authorizationCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.authorization_code_metadata
     *
     * @param authorizationCodeMetadata the value for oauth2_authorization.authorization_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorizationCodeMetadata(byte[] authorizationCodeMetadata) {
        this.authorizationCodeMetadata = authorizationCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_value
     *
     * @return the value of oauth2_authorization.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAccessTokenValue() {
        return accessTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_value
     *
     * @param accessTokenValue the value for oauth2_authorization.access_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenValue(byte[] accessTokenValue) {
        this.accessTokenValue = accessTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.access_token_metadata
     *
     * @return the value of oauth2_authorization.access_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getAccessTokenMetadata() {
        return accessTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.access_token_metadata
     *
     * @param accessTokenMetadata the value for oauth2_authorization.access_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAccessTokenMetadata(byte[] accessTokenMetadata) {
        this.accessTokenMetadata = accessTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.oidc_id_token_value
     *
     * @return the value of oauth2_authorization.oidc_id_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getOidcIdTokenValue() {
        return oidcIdTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.oidc_id_token_value
     *
     * @param oidcIdTokenValue the value for oauth2_authorization.oidc_id_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOidcIdTokenValue(byte[] oidcIdTokenValue) {
        this.oidcIdTokenValue = oidcIdTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.oidc_id_token_metadata
     *
     * @return the value of oauth2_authorization.oidc_id_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getOidcIdTokenMetadata() {
        return oidcIdTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.oidc_id_token_metadata
     *
     * @param oidcIdTokenMetadata the value for oauth2_authorization.oidc_id_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setOidcIdTokenMetadata(byte[] oidcIdTokenMetadata) {
        this.oidcIdTokenMetadata = oidcIdTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.refresh_token_value
     *
     * @return the value of oauth2_authorization.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getRefreshTokenValue() {
        return refreshTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.refresh_token_value
     *
     * @param refreshTokenValue the value for oauth2_authorization.refresh_token_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenValue(byte[] refreshTokenValue) {
        this.refreshTokenValue = refreshTokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.refresh_token_metadata
     *
     * @return the value of oauth2_authorization.refresh_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getRefreshTokenMetadata() {
        return refreshTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.refresh_token_metadata
     *
     * @param refreshTokenMetadata the value for oauth2_authorization.refresh_token_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRefreshTokenMetadata(byte[] refreshTokenMetadata) {
        this.refreshTokenMetadata = refreshTokenMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.user_code_value
     *
     * @return the value of oauth2_authorization.user_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getUserCodeValue() {
        return userCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.user_code_value
     *
     * @param userCodeValue the value for oauth2_authorization.user_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setUserCodeValue(byte[] userCodeValue) {
        this.userCodeValue = userCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.user_code_metadata
     *
     * @return the value of oauth2_authorization.user_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getUserCodeMetadata() {
        return userCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.user_code_metadata
     *
     * @param userCodeMetadata the value for oauth2_authorization.user_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setUserCodeMetadata(byte[] userCodeMetadata) {
        this.userCodeMetadata = userCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.device_code_value
     *
     * @return the value of oauth2_authorization.device_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getDeviceCodeValue() {
        return deviceCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.device_code_value
     *
     * @param deviceCodeValue the value for oauth2_authorization.device_code_value
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDeviceCodeValue(byte[] deviceCodeValue) {
        this.deviceCodeValue = deviceCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization.device_code_metadata
     *
     * @return the value of oauth2_authorization.device_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public byte[] getDeviceCodeMetadata() {
        return deviceCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization.device_code_metadata
     *
     * @param deviceCodeMetadata the value for oauth2_authorization.device_code_metadata
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setDeviceCodeMetadata(byte[] deviceCodeMetadata) {
        this.deviceCodeMetadata = deviceCodeMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", registeredClientId=").append(registeredClientId);
        sb.append(", principalName=").append(principalName);
        sb.append(", authorizationGrantType=").append(authorizationGrantType);
        sb.append(", authorizedScopes=").append(authorizedScopes);
        sb.append(", state=").append(state);
        sb.append(", authorizationCodeIssuedAt=").append(authorizationCodeIssuedAt);
        sb.append(", authorizationCodeExpiresAt=").append(authorizationCodeExpiresAt);
        sb.append(", accessTokenIssuedAt=").append(accessTokenIssuedAt);
        sb.append(", accessTokenExpiresAt=").append(accessTokenExpiresAt);
        sb.append(", accessTokenType=").append(accessTokenType);
        sb.append(", accessTokenScopes=").append(accessTokenScopes);
        sb.append(", oidcIdTokenIssuedAt=").append(oidcIdTokenIssuedAt);
        sb.append(", oidcIdTokenExpiresAt=").append(oidcIdTokenExpiresAt);
        sb.append(", refreshTokenIssuedAt=").append(refreshTokenIssuedAt);
        sb.append(", refreshTokenExpiresAt=").append(refreshTokenExpiresAt);
        sb.append(", userCodeIssuedAt=").append(userCodeIssuedAt);
        sb.append(", userCodeExpiresAt=").append(userCodeExpiresAt);
        sb.append(", deviceCodeIssuedAt=").append(deviceCodeIssuedAt);
        sb.append(", deviceCodeExpiresAt=").append(deviceCodeExpiresAt);
        sb.append(", attributes=").append(attributes);
        sb.append(", authorizationCodeValue=").append(authorizationCodeValue);
        sb.append(", authorizationCodeMetadata=").append(authorizationCodeMetadata);
        sb.append(", accessTokenValue=").append(accessTokenValue);
        sb.append(", accessTokenMetadata=").append(accessTokenMetadata);
        sb.append(", oidcIdTokenValue=").append(oidcIdTokenValue);
        sb.append(", oidcIdTokenMetadata=").append(oidcIdTokenMetadata);
        sb.append(", refreshTokenValue=").append(refreshTokenValue);
        sb.append(", refreshTokenMetadata=").append(refreshTokenMetadata);
        sb.append(", userCodeValue=").append(userCodeValue);
        sb.append(", userCodeMetadata=").append(userCodeMetadata);
        sb.append(", deviceCodeValue=").append(deviceCodeValue);
        sb.append(", deviceCodeMetadata=").append(deviceCodeMetadata);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}