package com.example.authserver.model;

import java.io.Serializable;

public class Oauth2AuthorizationConsent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization_consent.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String registeredClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization_consent.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String principalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization_consent.authorities
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private String authorities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization_consent.registered_client_id
     *
     * @return the value of oauth2_authorization_consent.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getRegisteredClientId() {
        return registeredClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization_consent.registered_client_id
     *
     * @param registeredClientId the value for oauth2_authorization_consent.registered_client_id
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setRegisteredClientId(String registeredClientId) {
        this.registeredClientId = registeredClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization_consent.principal_name
     *
     * @return the value of oauth2_authorization_consent.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization_consent.principal_name
     *
     * @param principalName the value for oauth2_authorization_consent.principal_name
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth2_authorization_consent.authorities
     *
     * @return the value of oauth2_authorization_consent.authorities
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth2_authorization_consent.authorities
     *
     * @param authorities the value for oauth2_authorization_consent.authorities
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization_consent
     *
     * @mbg.generated Thu Aug 31 10:45:16 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", registeredClientId=").append(registeredClientId);
        sb.append(", principalName=").append(principalName);
        sb.append(", authorities=").append(authorities);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}